# Generated by Django 2.1.1 on 2018-09-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snakeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snake',
            old_name='text',
            new_name='notes',
        ),
    ]
