# Generated by Django 2.1.1 on 2018-09-24 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snakeapp', '0002_auto_20180923_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snake',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='snake',
            name='hatch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
